### ISSUE TITLE
Key is not an element in the map for 6.0.1

### ISSUE THREAD

**Issue by iamwilhelm** [jxxcarlson/elm-text-editor#42]
Tried to install from 6.0.1 package. Got the following error:

```
[./src/Main.elm] 879 bytes {app} [built] [failed] [1 error]
    + 43 hidden modules

ERROR in ./src/Main.elm
Module build failed (from ./node_modules/elm-webpack-loader/index.js):
Error: Compiler process exited with error Compilation failed
Success! Compiled 1 module.                                          
elm: Map.!: given key is not an element in the map
CallStack (from HasCallStack):
  error, called at libraries/containers/Data/Map/Internal.hs:603:17 in containers-0.5.10.2:Data.Map.Internal

    at ChildProcess.<anonymous> (/Users/iamwil/projects/code/orb/node_modules/node-elm-compiler/dist/index.js:131:35)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
 @ multi ./src/Main.elm ./src/index.js app[0]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
       4 modules
```

It looks like it's an internal error? Unless I did it wrong somehow. To reproduce, create the following `Main.elm` and try to run it. It doesn't do much, just tries to include the EditorMsg, and handle it in the update. 

```
port module Main exposing (Model, Msg(..), init, main, subscriptions, update, view)

import Array exposing (Array)
import Browser
import Browser.Navigation as Nav
import Debug exposing (log, toString)
import Dict exposing (Dict)
import Editor exposing (Editor, EditorConfig, EditorMsg)
import Editor.Config exposing (WrapOption(..))
import Editor.Strings
import Html exposing (..)
import Html.Attributes exposing (..)
import Html.Events exposing (..)
import Json.Decode as D
import Json.Encode as E
import Url



-- MAIN


main : Program () Model Msg
main =
    Browser.application
        { init = init
        , view = view
        , update = update
        , subscriptions = subscriptions
        , onUrlChange = UrlChanged
        , onUrlRequest = LinkClicked
        }



-- MODEL


type alias Model =
    { key : Nav.Key
    , url : Url.Url
    }


init : () -> Url.Url -> Nav.Key -> ( Model, Cmd Msg )
init flags url key =
    ( { key = key
      , url = url
      }
    , Cmd.none
    )



-- UPDATE


type Msg
    = LinkClicked Browser.UrlRequest
    | UrlChanged Url.Url
    | EditorMsg EditorMsg


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        LinkClicked urlRequest ->
            case urlRequest of
                Browser.Internal url ->
                    ( model, Nav.pushUrl model.key (Url.toString url) )

                Browser.External href ->
                    ( model, Nav.load href )

        UrlChanged url ->
            ( { model | url = url }
            , Cmd.none
            )

        EditorMsg editorMsg ->
            ( model, Cmd.none )



-- SUBSCRIPTIONS


subscriptions : Model -> Sub Msg
subscriptions _ =
    Sub.none



-- VIEW


view : Model -> Browser.Document Msg
view model =
    { title = "App"
    , body =
        [ h1 [] [ text "hello" ]
        ]
    }
```

**Comment by jxxcarlson** [comment]
Just saw this -- will investigate.  Am going to try running your example now.

**Comment by jxxcarlson** [comment]
I tried running your code, but got this error:

```
This module does not declare any ports, but it says it will:

1| port module Main exposing (Model, Msg(..), init, main, subscriptions, update, view)
```

The [latest version](https://github.com/jxxcarlson/elm-text-editor.git) is 7.0.1.  Yesterday I learned how to manage projects with `npm`, so you should be able to download the repo and just do 

```bash
 npm install
 npm start
```

Please let me know if this works for you.  So sorry for the delay in responding.

-- Jim

**Comment by jxxcarlson** [comment]
Im at version 7.0.6 now.  I've verified that both `demo` and `demo-simple` work with `npm install` followed by `npm start`.

I'll close these issues, but if there is a problem, please let me know.

**Comment by iamwilhelm** [comment]
Ah, I didn't read the error closely. I was also able to build using `elm build`, the issue is with `elm-webpack-loader`. As of now, I can't use editor, since I wanted to stick with using the webpack loading for build:watch. 

It's not your responsibility to fix elm-webpack-loader. But if in the future, for reference, this was the webpack.config I used.

```
const path = require("path");
const { CleanWebpackPlugin } = require("clean-webpack-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
  mode: "development",
  devtool: "inline-source-map",
  entry: {
    app: ["./src/Main.elm", "./src/index.js"]
  },
  output: {
    filename: "[name].bundle.js",
    path: path.resolve(__dirname, "dist")
  },
  resolve: {
    extensions: [".js", ".elm"],
    modules: ["node_modules"]
  },
  plugins: [
    new CleanWebpackPlugin(),
    new HtmlWebpackPlugin({
      template: "public/index.html",
      inject: "body",
      filename: "index.html"
    })
  ],
  module: {
    rules: [
      {
        test: /\.elm$/,
        exclude: [/elm-stuff/, /node_modules/],
        use: {
          loader: "elm-webpack-loader",
          options: {
            verbose: true,
            debug: true
          }
        }
      },
      {
        test: /\.css$/,
        use: ["style-loader", "css-loader"]
      },
      {
        test: /\.scss$/,
        use: [
          {
            loader: "style-loader" // inject CSS to page
          },
          {
            loader: "css-loader" // translates CSS into CommonJS modules
          },
          {
            loader: "postcss-loader", // Run postcss actions
            options: {
              plugins: function() {
                // postcss plugins, can be exported to postcss.config.js
                return [require("autoprefixer")];
              }
            }
          },
          {
            loader: "sass-loader" // compiles Sass to CSS
          }
        ]
      }
    ]
  },
  // @dev needed to include this, to include d-eng
  node: {
    fs: "empty"
  }
};

```
